// import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 140,
    company: "Nike",
    color: "white",
    amount: 1,
    category: "sneakers",
  },

  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 340,
    company: "Adidas",
    color: "black",
    amount: 1,
    category: "sneakers",
  },

  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 140,
    amount: 1,
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 150,
    company: "Puma",
    color: "black",
    amount: 1,
    category: "sneakers",
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 180,
    amount: 1,
    company: "Puma",
    color: "white",
    category: "sneakers",
  },

  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 170,
    company: "Puma",
    amount: 1,
    color: "green",
    category: "sneakers",
  },
  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 220,
    company: "Vans",
    amount: 1,
    color: "red",
    category: "flats",
  },
  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 300,
    company: "Vans",
    amount: 1,
    color: "white",
    category: "sandals",
  },
  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 340,
    company: "Vans",
    amount: 1,
    color: "blue",
    category: "sandals",
  },

  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: "$110,00",
    company: "Vans",
    amount: 1,
    color: "black",
    category: "heels",
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 280,
    company: "puma",
    amount: 1,
    color: "black",
    category: "heels",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 130,
    company: "Nike",
    amount: 1,
    color: "red",
    category: "heels",
  },
  {
    id: 13,
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 115,
    company: "Nike",
    amount: 1,
    color: "red",
    category: "sneakers",
  },

  {
    id: 14,
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 170,
    company: "Nike",
    amount: 1,
    color: "black",
    category: "heels",
  },
  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 240,
    company: "Adidas",
    amount: 1,
    color: "black",
    category: "heels",
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 150,
    company: "Adidas",
    amount: 1,
    color: "white",
    category: "heels",
  },
  {
    id: 17,
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 110,
    company: "Adidas",
    amount: 1,
    color: "black",
    category: "heels",
  },
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    price: 190,
    company: "Adidas",
    amount: 1,
    color: "black",
    category: "flats",
  },
];

export default data;
